EnsJobeetBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: EnsJobeetBundle:Default:index }

EnsJobeetBundle_ens_job:
        resource: "@EnsJobeetBundle/Resources/config/routing/job.yml"
        prefix:   /ens_job
