# src/Blogger/BlogBundle/Resources/config/config.yml
parameters:
    # dirección de correo electrónico para contacto del Blogger
    blogger_blog.emails.from_email: richpolis@gmail.com
    # dirección de correo electrónico para contacto del Blogger
    blogger_blog.emails.to_email: richpolis@hotmail.com
    # Blogger máximo de comentarios recientes
    blogger_blog.comments.latest_comment_limit: 10